// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXzYwg9kSnU5ZEfdUh-W20k19PbxYaCOw',
    appId: '1:425830909312:android:0e277fd0804ae7a43a6d65',
    messagingSenderId: '425830909312',
    projectId: 'kneehapp-5f5ff',
    storageBucket: 'kneehapp-5f5ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkBcGzrPUK3TZ3bzBiCDjeoK5nEVqZuWM',
    appId: '1:425830909312:ios:e0f9f98e6c6072393a6d65',
    messagingSenderId: '425830909312',
    projectId: 'kneehapp-5f5ff',
    storageBucket: 'kneehapp-5f5ff.appspot.com',
    iosClientId:
        '425830909312-g3dd4l29oh6rvm8k02jkg18psfb3ctm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bachelorprojekt',
  );
}
